[package]
name = "flacenc"
version = "0.2.0"
description = "FLAC encoder written in Rust."
documentation = "https://docs.rs/flacenc/latest/flacenc"
readme = "README.md"
license = "Apache-2.0"
edition = "2021"
keywords = ["flac", "lossless", "encoder", "audio"]
categories = ["compression", "multimedia::audio", "multimedia::encoding"]
repository = "https://github.com/yotarok/flacenc-rs/"

# This is for enabling use of profilers with a release build.
[profile.release]
debug = 1

[features]
default = ["par"]
experimental = ["dep:nalgebra"]
par = ["dep:crossbeam-channel"]
fakesimd = []
mimalloc = ["dep:mimalloc"]
test_helper = ["dep:claxon", "dep:once_cell", "dep:rand", "dep:tempfile"]

[dependencies]
crc = "2.1"
crossbeam-channel = { version = "0.5.8", optional = true }
heapless = "0.7.10"
md5 = "0.7.0"
mimalloc = { version = "0.1.39", default-features = false, optional = true }
nalgebra = { version = "0.31", optional = true }
num-traits = "0.2"
seq-macro = "0.3"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"

# Followings are pasted from "dev-dependencies" for "test_helper" feature,
# that enables "test_helper" submodule in a release build. This is done for
# doctest where "cargo test --doc" build the crate to be tested with a normal
# config flags. There must be a better way to avoid this issue.
claxon = { version = "0.4.3", optional = true }
once_cell = { version = "1.10.0", optional = true }
rand = { version = "0.8.5", optional = true }
tempfile = { version = "3", optional = true }

[dev-dependencies]
bitvec = "1.0.0"
claxon = "0.4.3"
hound = "3.5.0"
once_cell = "1.10.0"
rand = "0.8.5"
rstest = "0.13.0"
tempfile = "3"
