name: Unittest

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    - name: Install external dependencies
      run: sudo apt-get install -y libsndfile1-dev
    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose

  lints:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    - name: Code format check
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --check
    - name: Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --tests -- -D warnings
    - name: Generate docs (for doc syntax checking)
      run: cargo doc
