name: Unittest

on:
  schedule:
    - cron: '0 4 * * *'  # runs at 4 AM UTC (13:00 JST)
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install latest nightly
      # uses: actions-rs/toolchain@v1
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt, clippy
    - name: Run tests
      uses: ClementTsang/cargo-action@v0.0.3
      with:
        command: test
        args: --verbose --all-targets --all-features
    - name: Run tests (CLI)
      uses: ClementTsang/cargo-action@v0.0.3
      with:
        command: test
        args: --verbose --all-targets --all-features
        directory: flacenc-bin

  build_stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install latest stable
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
    - name: Run tests
      uses: ClementTsang/cargo-action@v0.0.3
      with:
        command: test
        args: --verbose --all-targets --features fakesimd
    - name: Run tests (CLI)
      uses: ClementTsang/cargo-action@v0.0.3
      with:
        command: test
        args: --verbose --all-targets --features fakesimd
        directory: flacenc-bin

  lints:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install latest nightly
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt, clippy
    - name: Code format check
      uses: ClementTsang/cargo-action@v0.0.3
      with:
        command: fmt
        args: --check
    - name: Clippy
      uses: ClementTsang/cargo-action@v0.0.3
      with:
        command: clippy
        args: --tests -- -D warnings
    - name: Generate docs (for doc syntax checking)
      run: cargo doc
    - name: Code format check (CLI tools)
      uses: ClementTsang/cargo-action@v0.0.3
      with:
        command: fmt
        args: --check
        directory: flacenc-bin
    - name: Clippy (CLI tools)
      uses: ClementTsang/cargo-action@v0.0.3
      with:
        command: clippy
        args: --tests -- -D warnings
        directory: flacenc-bin
    - name: Clippy (with fakesimd feature)
      uses: ClementTsang/cargo-action@v0.0.3
      with:
        command: clippy
        args: --tests --features "fakesimd" -- -D warnings
